### PR TITLE
New methods and cleanup

### PR DESCRIPTION
**Pull request by l3d00m**

### CODE REVIEW

**Comment by l3d00m** [comment]
Sorry, wasn't meant to be opened here. Feel free to pick some commits of this though and merge it into your repository!

**Comment by ligi** [comment]
Why wasn't this meant to be opened here - here else would you want to open it ?-)
Thanks for the PR anyway - like the changes - was just sad for the removal of smileys - but perhaps it is for the better ..

**Comment by l3d00m** [comment]
I was trying something on my local branch, and opened it accidentally. Cool to see that you merged it in though!

Yeah, sorry for the smiley removal, but I liked it better without :p 

We are looking into using it for our app, [Slide for reddit](https://github.com/ccrama/Slide), which is why I started developing. I'll open another PR if there's something more I've implemented!

**Comment by ligi** [comment]
thanks for the info! 
Wanted to wait with bumping the version-number when it is fully propagated in bintray - should be done by now - thanks for the reminder ;-)

**Pull request merged**
